### ISSUE TITLE
感想

### ISSUE THREAD

**Issue by leefj** [asheigithub/apple-juice-actionscript#1]
一只在搜索有没有AS3动态解释执行的方案，看到你这个可惜是.NET的，如果能用AS3去解释执行AS3，就好了。

**Comment by asheigithub** [comment]
as3的有ascript,只是没我的全面。另外as3本身性能可能是略差点

**Comment by asheigithub** [comment]
其实我这个实现里面，没有使用太多.net的特性，移植as3应该也是可以的，有耐心即可

**Comment by leefj** [comment]
ascript还有一些没有支持的很好，自己去改，还没到那个能力

**Comment by asheigithub** [comment]
用as3本身动态解释执行as3,大概也只有air在ios热更这一个用处了吧。。。

**Comment by leefj** [comment]
对的，没错

**Comment by leefj** [comment]
现在用AIR做移动应用的多吗？

**Comment by asheigithub** [comment]
不知道。。。我们最后一个air项目是手游，没上线。。。然后就用unity了。其实air是蛮好用，但是adobe 不争气我们也没办法

**Comment by leefj** [comment]
Adobe更新的还是比较勤快的；就是给人的感觉还是心里没底。

**Comment by leefj** [comment]
Haxe和OpenFL怎么样？

**Comment by asheigithub** [comment]
这个没用过，不了解。。

**Comment by leefj** [comment]
哦哦
